name: care_and_cure
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text_pk: ^3.0.0
  cloud_firestore: ^2.5.1
  cupertino_icons: ^1.0.2
  syncfusion_flutter_charts: ^19.2.51
  data_table_2: ^2.1.1
  google_fonts: ^2.1.0
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  google_sign_in: ^5.0.7
  google_sign_in_web: ^0.10.0+2
  provider: ^6.0.0
  sizer: ^2.0.13
  websafe_svg: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/Icons/
   
  fonts:
    - family: OnePlus-Regular
      fonts:
        - asset: assets/fonts/OnePlus-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700